version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity
    links:
      - pgdb
     
      
    environment:
      PGHOST: pgdb
      PGDATABASE: postgres
      PGUSER: docker
      PGPASSWORD: docker
      PYTHONPATH: /workspace/src
      PGPORT: 5432
    
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
 
        
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports: 
  #     - 8080:80
  #   links:
  #     - pgdb
  #   volumes:
  #     - ~/.pgadmincompose:/var/lib/pgadmin

  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: hung135@hotmail.com
  #       PGADMIN_DEFAULT_PASSWORD: docker
  #       PGADMIN_LISTEN_PORT: 80  